const BANK = [
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 1, "q": "Under Article 324(5) of the Constitution, the Chief Election Commissioner can be removed from office:", "o": ["By the President at pleasure", "In the same manner and on the same grounds as a Judge of the Supreme Court", "Only by the Chief Justice of India", "By a simple majority of Parliament"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 2, "q": "The constitutional provision directly dealing with the removal protection of the Chief Election Commissioner is:", "o": ["Article 320", "Article 324(5)", "Article 326", "Article 329"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 3, "q": "The grounds for removal of a Supreme Court Judge, and consequently of the CEC, are:", "o": ["Violation of the Model Code of Conduct only", "Proved misbehaviour or incapacity", "Loss of majority support in Parliament", "Any disagreement with the Union Government"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 4, "q": "Which constitutional provision lays down the parliamentary address procedure for removal of a Supreme Court Judge?", "o": ["Article 124(4)", "Article 136", "Article 143", "Article 148"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 5, "q": "A motion for presenting an address for removal of a Judge may be initiated after notice signed by at least:", "o": ["50 Lok Sabha members or 100 Rajya Sabha members", "100 Lok Sabha members or 50 Rajya Sabha members", "75 members of either House", "25 members of either House"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 6, "q": "Who formally removes a Supreme Court Judge after both Houses pass the required address?", "o": ["The Chief Justice of India", "The Prime Minister", "The President", "The Speaker of Lok Sabha"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 7, "q": "Under Article 324(5), an Election Commissioner other than the CEC may be removed:", "o": ["Only after a joint sitting of Parliament", "Only on the recommendation of the CEC", "By the Prime Minister directly", "Only by the Supreme Court"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 8, "q": "The second proviso to Article 324(5) also covers:", "o": ["Members of Parliament", "Regional Commissioners", "State Election Commissioners", "Returning Officers"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 9, "q": "The statutory provision reproducing the removal rules for the CEC and other ECs is Section 11 of the:", "o": ["Representation of the People Act, 1951", "Election Commission Act, 1991", "Chief Election Commissioner and Other Election Commissioners Act, 2023", "Judges (Inquiry) Act, 1956"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 10, "q": "Under Section 11(1) of the 2023 Act, a CEC or EC resigns by writing addressed to the:", "o": ["Chief Justice of India", "Prime Minister", "President", "Speaker of Lok Sabha"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 11, "q": "The Chief Election Commissioner and Other Election Commissioners Act, 2023 replaced the:", "o": ["Representation of the People Act, 1951", "Election Commission (Conditions of Service of Election Commissioners and Transaction of Business) Act, 1991", "Judges (Inquiry) Act, 1968", "Presidential and Vice-Presidential Elections Act, 1952"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 12, "q": "Under Article 324(5), the conditions of service of the CEC cannot be varied to his or her disadvantage:", "o": ["Before appointment only", "After appointment", "Only during an election year", "Only with Parliament's permission"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 13, "q": "Which institution conducts elections to Parliament and State Legislatures under Article 324?", "o": ["Election Commission of India", "Union Public Service Commission", "Finance Commission", "Inter-State Council"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 14, "q": "The constitutional appointment of the CEC and other ECs is made by the:", "o": ["President, subject to parliamentary law", "Chief Justice of India", "Lok Sabha Speaker", "Rajya Sabha Chairman"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "CLAT-style — first 15", "number": 15, "q": "In March 2026, the Lok Sabha notice seeking removal of CEC Gyanesh Kumar was signed by how many members according to the Lok Sabha bulletin?", "o": ["50", "63", "100", "130"], "a": 3},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 16, "q": "Which sequence correctly describes the CEC removal framework?", "o": ["Article 324(5) → Article 124(4) → Judges (Inquiry) Act, 1968", "Article 324(5) → Article 356 → RPA, 1951", "Article 324(2) → Article 143 → CEC Act, 2023", "Article 329 → Article 124(5) → Representation of People Act"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 17, "q": "A notice for removal of the CEC is signed by 99 Lok Sabha members. Under the Judges (Inquiry) Act threshold, which statement is correct?", "o": ["It automatically proceeds to inquiry", "It is sufficient if the Rajya Sabha Chairman agrees", "It does not meet the minimum 100-member Lok Sabha threshold for such notice", "It must be converted into a joint sitting"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 18, "q": "A notice signed by 50 Rajya Sabha members is presented for removal of the CEC. Which statement is most accurate?", "o": ["The numerical threshold for giving notice is met, but admission and subsequent statutory procedure still have to be followed", "The CEC is automatically removed", "The motion must first be approved by the Chief Justice of India", "The President must immediately issue a removal order"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 19, "q": "Suppose Parliament passes an ordinary law allowing the Union Government to remove the CEC at pleasure. Which constitutional provision creates the direct obstacle?", "o": ["Article 324(5)", "Article 325", "Article 327", "Article 328"], "a": 0},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 20, "q": "Which distinction is constitutionally significant?", "o": ["CEC and other ECs have identical removal procedures", "CEC has Supreme-Court-Judge-level removal protection; other ECs require CEC recommendation", "Other ECs have stronger removal protection than the CEC", "Regional Commissioners are removable only by Parliament"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 21, "q": "The 2023 Act provides that the CEC and other ECs hold office for six years or until age 65, whichever is earlier. What follows?", "o": ["A commissioner is automatically entitled to a fresh six-year term", "Age 65 can terminate the tenure before six years", "The term can never end before six years", "The President can extend the term beyond 65"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 22, "q": "Under the 2023 Act, an Election Commissioner later appointed as CEC may serve for more than six years in aggregate as EC plus CEC. True or false?", "o": ["True, because CEC tenure is separate", "True, if Parliament approves", "False; the aggregate period cannot exceed six years", "False; the aggregate period cannot exceed ten years"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 23, "q": "Which body was part of the interim appointment mechanism laid down by the Supreme Court in Anoop Baranwal (2023), but is not part of the statutory Selection Committee under the 2023 Act?", "o": ["Prime Minister", "Leader of Opposition in Lok Sabha", "Chief Justice of India", "President"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 24, "q": "As of 23 September 2026, the Supreme Court proceedings challenging the 2023 CEC appointment law resulted in:", "o": ["A final declaration striking down the Act", "A split decision on whether a larger Constitution Bench reference was warranted, with the matter placed before the CJI", "A unanimous dismissal with no further proceedings", "A presidential reference under Article 143"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 25, "q": "The 2026 Jaya Thakur proceedings principally challenge which feature of the 2023 framework?", "o": ["The existence of Article 324 itself", "The composition and related provisions of the statutory appointment mechanism", "The age of voting", "The delimitation of constituencies"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 26, "q": "Under the 2023 Act, the Selection Committee consists of the PM, the Lok Sabha LoP (or statutory substitute where applicable), and:", "o": ["The Chief Justice of India", "A Union Cabinet Minister nominated by the PM", "The Union Law Secretary", "The Speaker of Lok Sabha"], "a": 1},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 27, "q": "The Search Committee under the 2023 Act is headed by the:", "o": ["Chief Justice of India", "Cabinet Secretary", "Minister of Law and Justice", "Election Commissioner senior-most in rank"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 28, "q": "The Search Committee prepares a panel of how many persons for consideration by the Selection Committee?", "o": ["Three", "Four", "Five", "Seven"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 29, "q": "Which statement about the 2023 Selection Committee is correct?", "o": ["A vacancy automatically invalidates every recommendation", "A defect in its constitution automatically voids every appointment", "The Act says an appointment is not invalid merely because of a vacancy or defect in the Committee's constitution", "Only the CJI may cure a defect"], "a": 2},
  {"topic": "Constitutional provisions for removal of Election Commissioners", "section": "Technical / hard — next 15", "number": 30, "q": "Which statement best distinguishes the constitutional removal safeguard from the 2023 appointment framework?", "o": ["Both are entirely statutory", "Removal of the CEC remains constitutionally insulated by Article 324(5), while appointment is additionally regulated by Parliament under Article 324(2)", "Removal is controlled only by the 2023 Act", "Appointment is exclusively controlled by Article 124"], "a": 1},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 1, "q": "Digital India BHASHINI was launched in July 2022 under the:", "o": ["National Language Translation Mission", "National Education Mission", "Digital Literacy Mission", "National Manuscript Mission"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 2, "q": "BHASHINI primarily seeks to:", "o": ["Replace all Indian languages with one language", "Reduce language barriers to digital services and communication", "Digitise only Sanskrit manuscripts", "Provide only English-language government services"], "a": 1},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 3, "q": "BhashaDaan is associated with:", "o": ["Crowdsourcing multilingual language data for BHASHINI", "Water conservation", "Election funding", "Digital payments"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 4, "q": "How many languages are included in the Eighth Schedule of the Constitution?", "o": ["18", "20", "22", "24"], "a": 2},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 5, "q": "Which organisation launched the AI-powered Adi-Vaani initiative for tribal languages?", "o": ["Ministry of Tribal Affairs", "Ministry of Finance", "Ministry of External Affairs", "Ministry of Railways"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 6, "q": "Which set contains languages currently supported by Adi-Vaani as reported by the Government in March 2026?", "o": ["Gondi, Mundari, Bhili and Santali", "Tamil, Telugu, Kannada and Malayalam", "Pali, Prakrit, Sanskrit and Persian", "Kashmiri, Dogri, Maithili and Konkani"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 7, "q": "Which two languages were reported as being in the development phase of Adi-Vaani in March 2026?", "o": ["Kui and Garo", "Koya and Kokborok", "Mundari and Gondi", "Pali and Prakrit"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 8, "q": "BharatGen is best described as:", "o": ["A sovereign, government-supported multilingual and multimodal AI initiative", "A satellite-navigation programme", "A payment settlement system", "A water-management platform"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 9, "q": "Which of the following is a BharatGen domain-specific model/application name?", "o": ["Legal Param", "Jal Param", "Election Param", "Bhasha Param"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 10, "q": "The Central Institute of Indian Languages (CIIL) functions under the:", "o": ["Ministry of Education", "Ministry of Tribal Affairs", "Ministry of Culture only", "Ministry of Home Affairs"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 11, "q": "SPPEL stands for:", "o": ["Scheme for Protection and Preservation of Endangered Languages", "Scheme for Promotion of Public English Learning", "Special Programme for Preservation of Electronic Literature", "Scheme for Protection of Parliamentary Election Languages"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 12, "q": "LDC-IL is associated with:", "o": ["Linguistic Data Consortium for Indian Languages", "Local Digital Census of Indian Languages", "Language Development Council of India Law", "Linguistic Development Committee for International Languages"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 13, "q": "In April 2026, a BHASHINI workshop specifically focused on preservation and digital AI model development for which language?", "o": ["Pali", "Latin", "French", "Arabic"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 14, "q": "In April 2026, another BHASHINI workshop focused on preservation of which script/language ecosystem?", "o": ["Gurmukhi/Punjabi", "Roman/English", "Devanagari/Hindi only", "Arabic/Urdu only"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "CLAT-style — first 15", "number": 15, "q": "Which AI technique is directly relevant to converting recorded speech in an endangered language into machine-readable text?", "o": ["Automatic Speech Recognition", "Blockchain hashing", "Optical fibre routing", "Image compression only"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 16, "q": "Why are community-generated datasets particularly relevant to endangered-language AI?", "o": ["They can supply authentic linguistic usage, including vocabulary, speech and cultural context", "They eliminate the need for any linguistic validation", "They make all languages grammatically identical", "They remove the need for data governance"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 17, "q": "A digital archive contains oral histories in a low-resource language. Which pipeline most directly supports preservation plus future AI use?", "o": ["Record → transcribe/annotate → digitise/store with metadata → validate with speakers → build usable datasets", "Delete recordings after transcription → translate only into English", "Compress audio → discard metadata → publish anonymously", "Translate everything into Hindi → destroy originals"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 18, "q": "Which pairing is correct?", "o": ["BHASHINI—language technology; BhashaDaan—citizen data contribution", "BHASHINI—water supply; BhashaDaan—electoral rolls", "Adi-Vaani—monetary policy; BharatGen—railway safety", "SPPEL—tax collection; LDC-IL—telecom licensing"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 19, "q": "According to the Government's 2026 information, BHASHINI's National Hub for Language Technologies operates on:", "o": ["India's first fully vendor- and cloud-agnostic AI Sovereign Cloud", "Only a foreign public cloud with no Indian infrastructure", "A satellite-only network", "A blockchain-only architecture"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 20, "q": "Which of the following is NOT a normal language-AI preservation task?", "o": ["Creating speech/text corpora", "Building OCR or speech-recognition resources", "Documenting oral traditions", "Determining parliamentary election results"], "a": 3},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 21, "q": "BharatGen's 2026 text-model development was reported as covering all 22 scheduled Indian languages. Which statement is consistent with the reported architecture?", "o": ["It includes text, speech and vision-language capabilities", "It is restricted to text-only translation", "It is only a handwriting font library", "It is a satellite image classifier with no language component"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 22, "q": "A major risk when training AI on an endangered language is that:", "o": ["A small or unrepresentative dataset can encode errors, omissions or dialect bias", "AI automatically preserves every cultural nuance perfectly", "Synthetic data always has higher authenticity than community data", "Translation eliminates the need to preserve original recordings"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 23, "q": "The April 2026 Pali workshop was organised by the Digital India BHASHINI Division in collaboration with:", "o": ["Centre for Advanced Studies in Buddhist Studies, University of Delhi", "RBI", "Election Commission of India", "Central Water Commission"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 24, "q": "The Gurmukhi-focused April 2026 workshop highlighted the need for:", "o": ["Digitisation, dataset creation and linguistic validation", "Replacing Gurmukhi with Roman script", "Restricting Punjabi to offline use", "Removing community participation from language technology"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 25, "q": "Which combination most directly addresses the language barrier, digital barrier and literacy barrier together?", "o": ["Voice-first multilingual AI such as BHASHINI", "English-only text interfaces", "Paper-only service delivery", "A single national-language keyboard"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 26, "q": "A model trained only on highly formal written material may perform poorly in speech because:", "o": ["Spoken language contains pronunciation, accents, disfluencies and context not captured by the written corpus alone", "Written language contains no vocabulary", "Speech has no linguistic structure", "AI cannot process audio"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 27, "q": "Which is the strongest preservation principle for AI-assisted language work?", "o": ["Keep original community data and provenance while using AI for access, transcription, translation and discovery", "Replace all primary recordings with AI-generated text", "Treat model output as automatically authoritative", "Exclude native speakers from validation"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 28, "q": "Which current Government initiative is specifically aimed at documentation and digitalisation of tribal languages while also providing translation?", "o": ["Adi-Vaani", "Sujalam Bharat", "DigiLocker", "e-Courts"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 29, "q": "Which statement best captures the distinction between preservation and translation?", "o": ["Translation can increase access, but preservation also requires documenting and retaining the original linguistic material and context", "Translation alone guarantees preservation", "Preservation means deleting the source language after translation", "They are legally identical concepts"], "a": 0},
  {"topic": "Use of AI in language preservation", "section": "Technical / hard — next 15", "number": 30, "q": "A language has very little digitised text but substantial oral tradition. Which technology combination is most directly useful?", "o": ["Speech recording + ASR + human validation + corpus creation", "Only spell-checking English", "Only image resizing", "Only payment authentication"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 1, "q": "The Digital Personal Data Protection Act was enacted in:", "o": ["2019", "2021", "2023", "2025"], "a": 2},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 2, "q": "The DPDP Rules, 2025 were notified on:", "o": ["14 November 2025", "1 January 2025", "26 January 2026", "10 February 2026"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 3, "q": "Under the DPDP framework, the individual to whom personal data relates is called the:", "o": ["Data Principal", "Data Fiduciary", "Consent Manager", "Significant Data Fiduciary"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 4, "q": "An entity that determines the purpose and means of processing personal data is generally a:", "o": ["Data Fiduciary", "Data Principal", "Data Processor only", "Regional Commissioner"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 5, "q": "The Data Protection Board of India is established under Section 18 of the:", "o": ["Digital Personal Data Protection Act, 2023", "Information Technology Act, 2000 only", "Aadhaar Act, 2016", "RTI Act, 2005"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 6, "q": "The DPDP Rules, 2025 provide that Rules 1, 2 and 17–21 came into force:", "o": ["On publication in the Official Gazette", "One year later", "Eighteen months later", "Only after a parliamentary resolution"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 7, "q": "Under the notified DPDP Rules, Rule 4 comes into force:", "o": ["One year after publication of the Gazette", "Immediately on publication", "Three years after publication", "Only after a court order"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 8, "q": "Under the notified DPDP Rules, Rules 3, 5–16, 22 and 23 come into force:", "o": ["Eighteen months after Gazette publication", "Immediately", "Six months after publication", "Five years after publication"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 9, "q": "The Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Amendment Rules, 2026 primarily introduced a dedicated framework concerning:", "o": ["Synthetically generated information and related online harms", "Water quality", "Election delimitation", "Banking interest rates"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 10, "q": "The 2026 IT Rules amendment was notified through Gazette notification:", "o": ["G.S.R. 120(E)", "G.S.R. 846(E)", "G.S.R. 324(E)", "G.S.R. 2023(E)"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 11, "q": "The 2026 IT Rules amendment came into force on:", "o": ["20 February 2026", "10 February 2026", "1 April 2026", "14 November 2025"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 12, "q": "Under the amended IT Rules, SGI broadly refers to realistic audio/visual/audio-visual information that is:", "o": ["Artificially or algorithmically created/modified and appears indistinguishable from a natural person or real-world event", "Any photograph taken with a digital camera", "Any compressed video", "Any text message"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 13, "q": "Under the 2026 amendments, content falling within specified categories such as nudity, morphed content and impersonation must generally be removed/disabled against a complaint within:", "o": ["2 hours", "3 hours", "36 hours", "7 days"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 14, "q": "Where an intermediary receives actual knowledge through a court order or authorised government intimation under the amended Rule 3(1)(d), the specified unlawful information must generally be removed/disabled within:", "o": ["3 hours", "2 hours", "24 hours", "36 hours"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "CLAT-style — first 15", "number": 15, "q": "The general grievance-resolution timeline under the amended Rule 3(2)(a)(i) was reduced to:", "o": ["7 days", "15 days", "36 hours", "30 days"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 16, "q": "The DPDP framework distinguishes the Data Principal from the Data Fiduciary. Which pairing is correct?", "o": ["Individual to whom data relates—Data Principal; entity deciding purpose and means—Data Fiduciary", "Government only—Data Principal; citizen—Data Fiduciary", "Platform user—Data Fiduciary; platform—Data Principal", "Both terms mean the same thing"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 17, "q": "The DPDP Rules require a Data Fiduciary to notify the Data Protection Board of a personal data breach:", "o": ["Without delay initially, with specified detailed information within 72 hours unless a longer period is allowed", "Only after one year", "Only if the user complains", "Never"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 18, "q": "For children, the notified DPDP Rules generally require:", "o": ["Verifiable parental consent before processing personal data, subject to specified rules/exemptions", "Consent only from a school principal", "No consent under any circumstance", "Consent only from the Data Protection Board"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 19, "q": "A Significant Data Fiduciary must conduct a Data Protection Impact Assessment and comprehensive audit:", "o": ["At least once every year", "Once every ten years", "Only after a breach", "Only before incorporation"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 20, "q": "The 2026 IT Rules specifically clarify that lawful removal/disablement of information, including SGI, in compliance with the Rules:", "o": ["Does not by itself amount to violation of the safe-harbour conditions under Section 79(2)", "Automatically destroys all safe harbour", "Requires a Supreme Court order", "Is prohibited"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 21, "q": "The 2026 SGI framework requires intermediaries to address permissible synthetic content through measures including:", "o": ["Labelling, metadata/provenance/identifier requirements", "Deletion of all AI-generated content", "A ban on all synthetic media", "Only voluntary user comments"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 22, "q": "For Significant Social Media Intermediaries, the amended framework adds which combination regarding SGI?", "o": ["User declaration, technical verification before publication/display, and prominent labelling", "Only a monthly newspaper advertisement", "No additional duties", "Only offline verification"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 23, "q": "The DPDP Rules require a Data Fiduciary to publish a mechanism through which Data Principals can exercise rights such as access and erasure. This primarily reflects:", "o": ["Transparency and practical rights exercise", "Abolition of data rights", "Mandatory public disclosure of all personal data", "Election regulation"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 24, "q": "Under the DPDP Rules, certain processing records/logs relevant to specified purposes are required to be retained for at least:", "o": ["One year, subject to the Rules and other applicable law", "One week", "Three days", "Twenty years in every case"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 25, "q": "The 2026 IT Rules describe SGI exclusions for routine good-faith editing such as colour adjustment or noise reduction when such editing:", "o": ["Does not materially alter, distort or misrepresent the underlying substance, context or meaning", "Is performed by a government entity", "Uses only open-source software", "Is performed on paper"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 26, "q": "The 2026 amendments allow authorised government officers for certain Rule 3(1)(d) intimations at a senior level not below:", "o": ["Deputy Inspector General (DIG) rank, where specifically authorised", "Constable rank", "Tehsildar rank only", "Village officer rank"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 27, "q": "The DPDP Act's institutional enforcement body is designed as a:", "o": ["Digital-by-design Data Protection Board of India", "Constitution Bench of the Supreme Court", "Parliamentary Standing Committee", "State Election Commission"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 28, "q": "Which statement best describes the relationship between the DPDP Act, 2023 and DPDP Rules, 2025?", "o": ["The Act establishes the statutory framework; the Rules provide detailed operational requirements and phased commencement", "The Rules repeal the Act", "The Rules are a constitutional amendment", "The Act applies only to paper records"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 29, "q": "Which recent digital-governance change most directly addresses realistic AI-generated deepfakes on intermediaries?", "o": ["The IT Rules (Intermediary Guidelines and Digital Media Ethics Code) Amendment Rules, 2026", "The DPDP Act, 2023 alone", "The RTI Act, 2005", "The Companies Act, 2013"], "a": 0},
  {"topic": "Recent changes in India's digital governance framework", "section": "Technical / hard — next 15", "number": 30, "q": "A platform receives a qualifying complaint at 10:00 a.m. concerning specified morphed/impersonation content under the amended Rule 3(2)(b). By what time should the specified removal/disablement normally occur?", "o": ["By 12:00 noon", "By 1:00 p.m.", "By 10:00 a.m. the next day", "Within seven days"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 1, "q": "Jal Jeevan Mission was launched in:", "o": ["2016", "2018", "2019", "2021"], "a": 2},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 2, "q": "Jal Jeevan Mission is administered by the:", "o": ["Ministry of Jal Shakti", "Ministry of Rural Development", "Ministry of Housing and Urban Affairs", "Ministry of Environment, Forest and Climate Change"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 3, "q": "The Department responsible for JJM is the:", "o": ["Department of Drinking Water & Sanitation", "Department of Water Resources only", "Department of Rural Development", "Department of Panchayati Raj"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 4, "q": "JJM 2.0 was approved by the Union Cabinet on:", "o": ["10 March 2026", "26 January 2026", "15 August 2025", "10 March 2025"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 5, "q": "JJM 2.0 extends the Mission up to:", "o": ["December 2027", "December 2028", "March 2030", "December 2032"], "a": 1},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 6, "q": "The enhanced total outlay approved for JJM 2.0 is:", "o": ["₹3.60 lakh crore", "₹5.00 lakh crore", "₹8.69 lakh crore", "₹10.00 lakh crore"], "a": 2},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 7, "q": "The approved central assistance under JJM 2.0 is:", "o": ["₹2.08 lakh crore", "₹3.59 lakh crore", "₹5.10 lakh crore", "₹8.69 lakh crore"], "a": 1},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 8, "q": "JJM 2.0 shifts the mission from an infrastructure-centric approach toward a:", "o": ["Service-delivery and utility-based approach", "Defence procurement approach", "Urban-only approach", "Cash-transfer-only approach"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 9, "q": "The national digital framework introduced under JJM 2.0 is called:", "o": ["Sujalam Bharat", "Jal Setu Bharat", "Harit Bharat", "Neer Bharat"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 10, "q": "Under Sujalam Bharat, each village is to receive a unique:", "o": ["Sujal Gaon / Service Area ID", "Aadhaar Water Number", "Gram Census Code only", "Panchayat Tax ID"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 11, "q": "The digital mapping under Sujalam Bharat covers the water-supply system:", "o": ["From source to tap", "Only from reservoir to village", "Only household meters", "Only groundwater wells"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 12, "q": "The formal handover/commissioning mechanism involving Gram Panchayats and VWSCs is termed:", "o": ["Jal Arpan", "Jal Shakti Abhiyan", "Jal Jeevan Setu", "Har Ghar Survey"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 13, "q": "Under JJM 2.0, a Gram Panchayat may declare itself 'Har Ghar Jal' only after:", "o": ["Adequate in-village operation and maintenance mechanisms are established and confirmed", "A new district is created", "Every household buys a water purifier", "The village becomes urban"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 14, "q": "Jal Utsav under JJM 2.0 is envisaged as:", "o": ["An annual community-led maintenance and review event", "A national dam-construction festival", "A water-tax collection drive", "A one-time inauguration ceremony"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "CLAT-style — first 15", "number": 15, "q": "The baseline rural household tap-connection coverage cited by the Cabinet in 2019 was approximately:", "o": ["17%", "25%", "40%", "55%"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 16, "q": "Which of the following is a core institutional feature of JJM 2.0?", "o": ["State/UT reform-linked MoUs and structural reforms for sustainable service delivery", "Elimination of Gram Panchayats", "Centralisation of every village water scheme in the Union Government", "Restriction of community participation"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 17, "q": "The JJM 2.0 model gives an important role to which local institutions in commissioning and handover?", "o": ["Gram Panchayats and Village Water & Sanitation Committees", "Only Parliament", "Only municipal corporations", "Only district courts"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 18, "q": "Which phrase best captures the service standard sought by JJM 2.0?", "o": ["Reliable, adequate and safe drinking water services for rural households", "Occasional tanker supply only", "Urban piped water for selected villages", "Irrigation water for farms only"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 19, "q": "The 2026 JJM 2.0 reform-linked implementation emphasises:", "o": ["Gram Panchayat-led, service-based and community-centred rural water governance", "Only contractor-led construction", "Only household subsidies", "Only groundwater extraction"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 20, "q": "Which of the following is a JJM 2.0 digital-governance objective?", "o": ["End-to-end mapping of rural drinking-water infrastructure from source to tap", "Replacing all village records with paper", "Creating a national electricity grid", "Mapping parliamentary constituencies"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 21, "q": "Which states signed reform-linked JJM 2.0 MoUs on 20 March 2026 according to the Government release?", "o": ["Gujarat, Haryana, Chhattisgarh, Himachal Pradesh and Goa", "Kerala, Tamil Nadu, Punjab, Assam and Bihar", "Maharashtra, Rajasthan, Odisha, Delhi and Goa", "Uttar Pradesh, Rajasthan, Madhya Pradesh, Maharashtra and Karnataka"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 22, "q": "Andhra Pradesh and Odisha signed reform-linked JJM 2.0 MoUs on:", "o": ["24 March 2026", "10 March 2026", "1 April 2026", "29 April 2026"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 23, "q": "The Comprehensive Implementation and Reform Plan (CIRP) under JJM 2.0 serves as the principal framework for:", "o": ["Mission planning, prioritisation, reform implementation, fund allocation and monitoring", "Only household Aadhaar enrolment", "Only dam safety audits", "Only school sanitation"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 24, "q": "Which of the following best reflects the reason for JJM 2.0's restructuring?", "o": ["Physical infrastructure must be accompanied by sustainable operation, maintenance, governance and service delivery", "The original mission was designed only for cities", "The Union Government has ended rural water supply", "Water quality is no longer relevant"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 25, "q": "A village has completed pipelines but lacks an established local O&M mechanism. Under the JJM 2.0 approach, which conclusion follows?", "o": ["Completion of construction alone is insufficient for the Gram Panchayat's Har Ghar Jal certification", "The village must automatically be certified", "The scheme must be converted to an urban scheme", "The village becomes ineligible for all water services"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 26, "q": "What is the principal significance of Sujal Gaon / Service Area IDs?", "o": ["They create a digital identity for mapping and tracking the rural water-supply service area and system", "They are voter IDs", "They are land titles", "They are drinking-water quality certificates"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 27, "q": "Which funding figure represents the additional central share associated with the JJM 2.0 enhancement over the earlier approved central assistance?", "o": ["₹0.51 lakh crore", "₹1.51 lakh crore", "₹2.51 lakh crore", "₹3.59 lakh crore"], "a": 1},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 28, "q": "JJM 2.0's 'Whole of Government' approach is particularly linked to:", "o": ["Strategic convergence among departments for long-term O&M and source sustainability", "Abolishing state-level participation", "Moving all water functions to the judiciary", "Replacing rural institutions with private banks"], "a": 0},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 29, "q": "Which of the following is NOT a stated JJM 2.0 mechanism?", "o": ["Jal Arpan", "Jal Utsav", "Sujalam Bharat", "A nationwide parliamentary delimitation exercise"], "a": 3},
  {"topic": "Jal Jeevan Mission 2.0", "section": "Technical / hard — next 15", "number": 30, "q": "Which statement correctly connects the 2019 baseline and the 2028 target?", "o": ["JJM began from a reported 17% rural household tap-connection baseline and JJM 2.0 aims for universal rural household tap connections by December 2028", "JJM began at 100% and aims for 17%", "JJM began at 55% and aims for 60%", "JJM began only in urban areas"], "a": 0}
];

let all = [...BANK];
let current = 0;
let answered = false;
let score = 0;
let results = [];

function startTest() {
  document.getElementById('start').classList.add('hide');
  document.getElementById('test').classList.remove('hide');
  document.querySelector('.sources').classList.add('hide');
  loadQuestion();
}

function restartWithFilter() {
  const f = document.getElementById('topicFilter').value;
  all = f === 'ALL' ? [...BANK] : BANK.filter((x) => x.topic === f);
  current = 0;
  score = 0;
  results = [];
  loadQuestion();
}

function loadQuestion() {
  if (current >= all.length) return finish();

  answered = false;
  const x = all[current];

  document.getElementById('topic').textContent = x.topic;
  document.getElementById('section').textContent = x.section + ' • Q' + x.number;
  document.getElementById('question').textContent = x.q;
  document.getElementById('counter').textContent = `Question ${current + 1} of ${all.length}`;
  document.getElementById('bar').style.width = `${(current / all.length) * 100}%`;

  const box = document.getElementById('options');
  box.innerHTML = '';

  x.o.forEach((text, i) => {
    const b = document.createElement('button');
    b.className = 'opt';
    b.innerHTML = `<b>${String.fromCharCode(65 + i)}.</b> ${text}`;
    b.onclick = () => choose(i, b);
    box.appendChild(b);
  });

  const fb = document.getElementById('feedback');
  fb.textContent = '';
  fb.className = 'feedback';

  const nb = document.getElementById('nextBtn');
  nb.classList.remove('show');
}

function choose(i, button) {
  if (answered) return;

  answered = true;
  const x = all[current];
  const opts = [...document.querySelectorAll('.opt')];

  opts.forEach((b) => b.classList.add('locked'));
  opts[x.a].classList.add('correct');

  if (i === x.a) {
    score++;
    button.classList.add('correct');
    document.getElementById('feedback').textContent = 'Correct ✓';
    document.getElementById('feedback').className = 'feedback ok';
  } else {
    button.classList.add('wrong');
    document.getElementById('feedback').textContent = 'Incorrect — correct answer: ' + String.fromCharCode(65 + x.a) + '. ' + x.o[x.a];
    document.getElementById('feedback').className = 'feedback no';
  }

  results.push({ ...x, chosen: i, correct: i === x.a });
  document.getElementById('nextBtn').classList.add('show');
}

function nextQuestion() {
  current++;
  loadQuestion();
}

function finish() {
  document.getElementById('test').classList.add('hide');
  document.getElementById('result').style.display = 'block';
  document.querySelector('.sources').classList.remove('hide');

  document.getElementById('rTotal').textContent = all.length;
  document.getElementById('rCorrect').textContent = score;
  document.getElementById('rWrong').textContent = all.length - score;
  document.getElementById('rAccuracy').textContent = `${Math.round((score / all.length) * 100)}%`;

  const topics = [...new Set(all.map((x) => x.topic))];
  document.getElementById('topicAnalysis').innerHTML = topics.map((t) => {
    const r = results.filter((x) => x.topic === t);
    const c = r.filter((x) => x.correct).length;
    const percent = r.length ? Math.round((c / r.length) * 100) : 0;
    return `<div class="analysisRow"><span>${t}</span><b>${c}/${r.length} • ${percent}%</b></div>`;
  }).join('');

  const secs = [...new Set(all.map((x) => x.section))];
  document.getElementById('sectionAnalysis').innerHTML = secs.map((s) => {
    const r = results.filter((x) => x.section === s);
    const c = r.filter((x) => x.correct).length;
    const percent = r.length ? Math.round((c / r.length) * 100) : 0;
    return `<div class="analysisRow"><span>${s}</span><b>${c}/${r.length} • ${percent}%</b></div>`;
  }).join('');

  const wrong = results.filter((x) => !x.correct);
  document.getElementById('wrongReview').innerHTML = wrong.length
    ? wrong.map((x, i) => `
        <div class="wrongItem">
          <b>${i + 1}. ${x.topic} — Q${x.number}</b><br>
          ${x.q}<br>
          <span class="small">Your answer: ${String.fromCharCode(65 + x.chosen)}. ${x.o[x.chosen]}<br>
          Correct: ${String.fromCharCode(65 + x.a)}. ${x.o[x.a]}</span>
        </div>
      `).join('')
    : '<p><b>Perfect score on this run.</b> No questions to review.</p>';
}
